### ISSUE TITLE
[EN] Armenian Khatchkars (Cross-Stones) Database

### ISSUE THREAD

**Issue by vvbabayan** [opendataam/opendatam-tasks#28]
**Goal**
The goal is to extract the data about khatchkars of Armenia from a single source.

**Tasks**
The entry point for this task is the corresponding [Armenica database](http://www.armenica.org/cgi-bin/armenica.cgi?467864590376361=2=h) with khatchkars in 27 localities (cities or monasteries). Localities are given after pressing "Khatchkars (27)" on the left. For each of them, photos of khatchkars with some basic information are provided. The goal is to extract all that information in a machine-readable format, such as CSV or JSON, adding the location as a variable.

 
**Context**
The list of locations is complete, as is the information about khatchkars. However, this collection by Armenia is an important source for constructing a future database of Armenian khatchkars.

**Requirements**
A public GitHub repository should be created to store and publish the code and the data under one of the free and open licenses, such as Creative Commons or MIT.

**Wishes**
It would be best if your code is reusable, that is can be launch again by anyone who might want to update the dataset at a later point. For the same reason, we encourage you to comment your code, supplement it with at least a very brief README description, and specify the requirements and dependencies necessary to use the code.

**Resources**

1. [Armenica](http://www.armenica.org/cgi-bin/armenica.cgi?467864590376361=2=h)

**Prepared by**
The Open Data Armenia team prepared this task.

**Comment by vlivyur** [comment]
Here are [code](https://github.com/vlivyur/Khachkar) and [data](https://github.com/vlivyur/Khachkar.Data)

**Comment by vvbabayan** [comment]
@vlivyur Thank you so much! We will share the data in our catalogue soon.
